[theme]
# Spotify-style dark theme
base = "dark"
primaryColor = "#1DB954"  # Spotify Green
backgroundColor = "#191414"  # Spotify Black
secondaryBackgroundColor = "#282828"  # Dark Grey
textColor = "#FFFFFF"  # White
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false


